### ISSUE TITLE
Margin Utility Class

### ISSUE THREAD

**Issue by incompletude** [getpavilion/pavilion#11]
Most elements come configured with left to right margin scheme. It would be very useful when configuring right to left elements to have some utility class to change the margin side. 

I'm using with the following class with the first float-right, but not sure if there is a better way.

.no-margin-right {
    margin-right: 0;
}

**Comment by getpavilion** [comment]
Hi, thanks for your request. 

I see your point and I think your solution is fine! I won't add more utility classes to Pavilion because you will just end up with a lot of classes you don't use. I'd rather write the ones I need myself then.

Hope you understand :)

Kind regards,

Wessel
