### ISSUE TITLE
Suggestion: An Autocomplete Library for Atom

### ISSUE THREAD

**Issue by vilbht** [getpavilion/pavilion#4]
Hi

Just discovered Pavilion. Hope to use it in an upcoming project. Would be great to have an autocomplete helper package for Atom / Sublime for assistance with syntax discovery and memorization:

http://blog.atom.io/2015/05/15/new-autocomplete.html

Thanks!

**Comment by getpavilion** [comment]
Hi!

Great idea actually! 

I am currently working on a roadmap and that Idea will definitely be on it! 

Thanks for the input.

**Comment by getpavilion** [comment]
Added to the roadmap, see wiki
