### ISSUE TITLE
Dropcap errors with special characters

### ISSUE THREAD

**Issue by ghost** [getpavilion/pavilion#7]
I am using the `.dropcap` class on a `<p>` tag that starts with the text "`I'm a`". The issue is that the `'` character is also bolded and enlarged along with the `I`. Is is possible to set the number of characters that get added to the dropcap? I would like to either have the whole word or just the first letter. Many thanks.

**Comment by wesselgrift** [comment]
Hi chewzerita,

Unfortunately that is not possible with normal CSS. I'd suggest to add a space after the first letter to detach the `'` from the first character.

For custom options, look at this article: https://css-tricks.com/snippets/css/drop-caps/

Cheers
